PUT  http://localhost:2203/api/characters/edit
Content-Type: application/json


{
    "id_personaje": 4,
    "imagen_personaje":"aca deberia ir al imagen",
    "edad_personaje": 34,
    "peso_personaje": 123,
    "historia_personaje":"eeeee",
    "nombre_personaje": "golbin"
}